---
# TODO: implement start, stop and delete
- name: run Patchwork
  hosts: localhost
  vars:
    c_name: patchwork
    i_name: '{{ c_name }}-i'
    db_image: docker.io/centos/postgresql-96-centos7
    db_container: '{{ c_name }}-db'
    db_loader_container: '{{ c_name }}-db-loader'
    db_database_name: '{{ c_name }}'
    db_user: '{{ c_name }}'
    db_password: FIXME-generate-this  # ansible vault
  tasks:
    - name: build patchwork image
      docker_image:
        path: .
        name: '{{ i_name }}'
        tag: latest
        state: 'present'
        force: true
    - name: obtain postgres image
      docker_image:
        name: '{{ db_image }}'
        tag: latest
    - name: run postgres
      docker_container:
        name: '{{ db_container }}'
        image: '{{ db_image }}'
        state: 'started'
        restart_policy: always
        env:
          POSTGRESQL_USER: '{{ db_user }}'
          POSTGRESQL_PASSWORD: '{{ db_password }}'
          POSTGRESQL_DATABASE: '{{ db_database_name }}'
        # volumes:
        #   - '{{ db_container }}-data:/var/lib/mysql:z'
      register: db_cont_metadata
    # - debug:
    #     msg: '{{ db_cont_metadata }}'
    - name: wait for postgres to accept connections
      wait_for:
        host: '{{ db_cont_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
        port: 5432
        state: drained
        connect_timeout: 15
        timeout: 30
      register: postgres_running
      until: postgres_running | success
      retries: 10
    - name: populate the database
      docker_container:
        name: '{{ db_loader_container }}'
        image: '{{ i_name }}'
        state: 'started'
        env:
          DATABASE_NAME: '{{ db_database_name }}'
          DATABASE_USER: '{{ db_user }}'
          DATABASE_PASSWORD: '{{ db_password }}'
          DATABASE_HOST: '{{ db_cont_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
          DATABASE_PORT: '5432'
          DJANGO_SECRET_KEY: 'FIXME'  # utilize ansible vault
        command: ./init_db.sh
    - name: we can finally run patchwork
      docker_container:
        name: '{{ c_name }}'
        image: '{{ i_name }}'
        state: 'started'
        env:
          DATABASE_NAME: '{{ db_database_name }}'
          DATABASE_USER: '{{ db_user }}'
          DATABASE_PASSWORD: '{{ db_password }}'
          DATABASE_HOST: '{{ db_cont_metadata["ansible_facts"]["docker_container"]["NetworkSettings"]["IPAddress"] }}'
          DATABASE_PORT: '5432'
          DJANGO_SECRET_KEY: 'FIXME'
        ports:
          - 8000:8000
# TODO: smoke test web and database
